general.import = [
    "~/.config/alacritty/themes/coolnight.toml"
]

[env]
TERM="xterm-256color"
[window]
padding.x=10
padding.y=10

decorations="Buttonless"
opacity=0.9

[font]
normal.family="Hack Nerd Font Mono"
size=18

[[keyboard.bindings]]
key = "Space"
mods = "Control|Shift"
mode = "~Vi"
action = "ToggleViMode"
